#BE-4783 Add profile creation settings
appcircleio/fastlane_plugin_appcircle_testing_distribution pull request #7
Opened 2024-12-06 05:52 UTC by hiilhan

2024-12-10 12:05 UTC, burakberkkeskin approved these changes
Tested on dev environment:
- The profile created with static username password successfully. Shared with email and downloaded successfully.
- The profile created with non-auth successfully. Shared with email and downloaded successfully.

2024-12-16 13:06 UTC, csonuryilmaz requested changes

2024-12-16 13:06 UTC, csonuryilmaz commented on README.md
> +    subOrganizationName: "${AC_SUB_ORGANIZATION_NAME}",
`{` vs. `(` Which one should be?

2024-12-16 13:06 UTC, csonuryilmaz commented on README.md
> +      testingGroupNames: "AC_PROFILE_TESTING_GROUP_NAMES"
Fix

2024-12-16 13:06 UTC, csonuryilmaz commented on README.md
> +## Docs
```suggestion
## Further Details
```

2024-12-18 00:28 UTC, csonuryilmaz requested changes
@hiilhan I have added some threads to be resolved and one question to discuss.

In addition to those, please also fix the cases below.

1️⃣ Remove obsolete images from repository.
- `images/distribution-start.png`
- `images/PAT.png`

AFAIK, we are using the CDN URL in the README. Also, they might be stale.

2️⃣ The license should be owned by Appcircle instead of an individual contributor. You can check other samples from workflow step license files.

![Screenshot 2024-12-18 at 03 25 01](https://github.com/user-attachments/assets/b948598e-39db-494d-aa94-731565daba15)

3️⃣ Update the `version.rb` file to our target version: `0.3.2`. So, our PR will be ready for release when merged.

2024-12-18 00:28 UTC, csonuryilmaz commented on README.md
>  ```yml
It should be `ruby` instead of yaml.

2024-12-18 00:28 UTC, csonuryilmaz commented on lib/fastlane/plugin/appcircle_testing_distribution/helper/TDUploadService.rb
> +      # content_type: :multipart or multipart/form-data # Causing a type cast warning
❓ Are we sure about this change? Does it affect anything?

Content type might be an important argument in request headers.

2024-12-18 00:28 UTC, csonuryilmaz commented on lib/fastlane/plugin/appcircle_testing_distribution/helper/TDUploadService.rb
> +require_relative '../helper/appcircle_testing_distribution_helper'
AFAIK, we do not refer to any function from this helper ruby. So, it seems to be unnecessary to "require" the file here.

2024-12-18 00:28 UTC, csonuryilmaz commented on README.md
> +   - [Discover Action](https://docs.appcircle.io/marketplace/fastlane/testing-distribution#discover-action)
Markdown indentation should be 2 spaces instead of 3 spaces for unordered list items. (markdown lint)

2024-12-18 00:28 UTC, csonuryilmaz commented on README.md
> +   - `authType`: Authentication type of the profile. `none`: None, `static`: Static Username and Password, `ldap`: LDAP Login, `sso`: SSO Login.
Markdown indentation should be 2 spaces instead of 3 spaces for unordered list items. (markdown lint)

2024-12-18 06:24 UTC, hiilhan commented on README.md
>  ```yml
1. Done
2. Done
3. I was planning to bump version on release branch, since this is the feature branch. How do we usually handle this?

2024-12-18 06:25 UTC, hiilhan commented on lib/fastlane/plugin/appcircle_testing_distribution/helper/TDUploadService.rb
> +      # content_type: :multipart or multipart/form-data # Causing a type cast warning
Didn't effect the tests, I will check again.

2024-12-18 08:10 UTC, csonuryilmaz commented on fastlane/Fastfile
>      personalAPIToken: ENV["AC_ACCESS_TOKEN"],
Change to `AC_PERSONAL_API_TOKEN`

2024-12-18 08:11 UTC, csonuryilmaz commented on README.md
> +    personalAPIToken: ENV["AC_ACCESS_TOKEN"],
Change to `AC_PERSONAL_API_TOKEN`

2024-12-18 08:39 UTC, hiilhan commented on lib/fastlane/plugin/appcircle_testing_distribution/helper/TDUploadService.rb
> +      # content_type: :multipart or multipart/form-data # Causing a type cast warning
> Auto-detects that you have a File value sends it as multipart
> (from https://github.com/rest-client/rest-client#multipart)

Current payload has a File value but added `multipart: true`, to make sure.

2024-12-18 08:41 UTC, csonuryilmaz commented on lib/fastlane/plugin/appcircle_testing_distribution/helper/TDUploadService.rb
> +      # content_type: :multipart or multipart/form-data # Causing a type cast warning
OK. Thanks for the research and clarification.

2024-12-18 14:08 UTC, csonuryilmaz approved these changes

2024-12-18 14:12 UTC, merged