#BE-4784 Add testing groups option
appcircleio/fastlane_plugin_appcircle_testing_distribution pull request #8
Opened 2024-12-06 05:53 UTC by hiilhan

2024-12-10 12:13 UTC, burakberkkeskin submitted a review, later dismissed
Tested with a freshly created testing distribution profile.
- The TD profile is created ✅ 
- The "auto send" feature is enabled.
- The tester group(s) are added to the TD profile.
- The TD emails has been received by emails.

2024-12-11 14:39 UTC, burakberkkeskin requested changes
Some test cases have been failed. 
Details -> [Linear comment](https://linear.app/appcircle/issue/BE-4784/[fastlane-plugin]provide-an-option-to-input-the-testing-group-name-via#comment-782a8584)

2024-12-12 15:41 UTC, csonuryilmaz requested changes

2024-12-12 15:41 UTC, csonuryilmaz commented on README.md
> +      testingGroupNames: "AC_PROFILE_TESTING_GROUPS"
```suggestion
      testingGroupNames: "AC_PROFILE_TESTING_GROUP_NAMES"
```

2024-12-12 15:41 UTC, csonuryilmaz commented on fastlane/Fastfile
> +      testingGroupNames: ENV["AC_PROFILE_TESTING_GROUPS"]
```suggestion
      testingGroupNames: ENV["AC_PROFILE_TESTING_GROUP_NAMES"]
```

2024-12-12 15:41 UTC, csonuryilmaz commented on lib/fastlane/plugin/appcircle_testing_distribution/actions/appcircle_testing_distribution_action.rb
> +                                         value[:testingGroupNames] ||= ENV["AC_PROFILE_TESTING_GROUPS"]
```suggestion
                                         value[:testingGroupNames] ||= ENV["AC_PROFILE_TESTING_GROUP_NAMES"]
```

2024-12-16 09:42 UTC, merged