#BE-4921 Add sub organization name option
appcircleio/fastlane_plugin_appcircle_testing_distribution pull request #9
Opened 2024-12-09 06:31 UTC by hiilhan

2024-12-10 11:22 UTC, burakberkkeskin commented
Tested with a sub organization on dev environment with a valid APK/IPA.

2024-12-10 11:22 UTC, burakberkkeskin approved these changes
Tested with a sub organization on dev environment with a valid APK/IPA. LGTM!

2024-12-12 15:41 UTC, csonuryilmaz requested changes

2024-12-12 15:41 UTC, csonuryilmaz commented on lib/fastlane/plugin/appcircle_testing_distribution/helper/TDAuthService.rb
> +      raise "HTTP Request failed (#{response.code} #{response.message})"
```suggestion
      raise "Error: (#{response.code} #{response.message})"
```

2024-12-16 09:44 UTC, merged